# REMINDER: Change away from default creds before production!!!
# Also, avoid pushing actual credentials to GitHub.

[default]  
bville_db = { url = "mysql://runner:password@localhost/bville_recycle" }

[global]
log_level = "critical"
