name: Rust CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Set up MariaDB
      run: |
        sudo apt-get update
        sudo apt-get install -y mariadb-server
        sudo service mysql start
        
        # Configure MariaDB
        sudo mysql -e "CREATE DATABASE IF NOT EXISTS bville_recycle;"
        sudo mysql -e "DROP USER IF EXISTS '${{ secrets.DB_USER }}'@'localhost';"
        sudo mysql -e "CREATE USER '${{ secrets.DB_USER }}'@'localhost';"
        sudo mysql -e "SET PASSWORD FOR '${{ secrets.DB_USER }}'@'localhost' = PASSWORD('${{ secrets.DB_PASSWORD }}');"
        sudo mysql -e "GRANT ALL PRIVILEGES ON bville_recycle.* TO '${{ secrets.DB_USER }}'@'localhost';"
        sudo mysql -e "FLUSH PRIVILEGES;"

    - name: Create .env File
      run: |
        echo "DATABASE_URL=mysql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@localhost/bville_recycle" > .env

    - name: Build the Project
      run: cargo build --verbose

    - name: Run Tests
      run: cargo test --verbose
