# .github/workflows/unsafe.yml

name: Unsafe Forbidden

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unsafe_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Clippy
        run: rustup component add clippy
      - name: Check for Unsafe Code
        run: cargo clippy --all-targets --all-features -- --deny=unsafe_code
